language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - PUPPET_VERSION=3.0.2
install:
  - gem install bundler
  - bundle update
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.17
